/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazpi;

/**
 *
 * @author santi
 */
public class ViewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewJFrame
     */
    public ViewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBarraLateral = new javax.swing.JPanel();
        jLabelLogoBarra = new javax.swing.JLabel();
        jPanelMateriaPrima = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelProveedores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelEmpleados1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPaneMateriaPrimaTabbed = new javax.swing.JPanel();
        jPanelProductosTabbed = new javax.swing.JPanel();
        jPanelProveedoresTabbed = new javax.swing.JPanel();
        jPanelClientesTabbed = new javax.swing.JPanel();
        jPanelEmpleadosTabbed = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.Color.gray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraLateral.setBackground(new java.awt.Color(40, 70, 85));
        jPanelBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/logo peque.png"))); // NOI18N
        jPanelBarraLateral.add(jLabelLogoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 110));

        jPanelMateriaPrima.setBackground(new java.awt.Color(231, 231, 216));
        jPanelMateriaPrima.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/seeds_122867 (1).png"))); // NOI18N
        jPanelMateriaPrima.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel4.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 119, 119));
        jLabel4.setText("MATERIA PRIMA");
        jPanelMateriaPrima.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        jPanelProductos.setBackground(new java.awt.Color(231, 231, 216));
        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/d0e057c0f1324dffe016a4ec4ef1e928-icono-de-golpe-de-empanada.png"))); // NOI18N
        jPanelProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jLabel6.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 119, 119));
        jLabel6.setText("productos");
        jPanelProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        jPanelBarraLateral.add(jPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));
        jPanelProductos.getAccessibleContext().setAccessibleName("");

        jPanelProveedores.setBackground(new java.awt.Color(231, 231, 216));
        jPanelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/proveedor.png"))); // NOI18N
        jPanelProveedores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 119, 119));
        jLabel8.setText("PROVEEDORES");
        jPanelProveedores.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        jPanelClientes.setBackground(new java.awt.Color(231, 231, 216));
        jPanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/male3_85205.png"))); // NOI18N
        jPanelClientes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(127, 119, 119));
        jLabel10.setText("CLIENTES");
        jPanelClientes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 20));

        jPanelBarraLateral.add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        jPanelEmpleados.setBackground(new java.awt.Color(231, 231, 216));
        jPanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/empleado.png"))); // NOI18N
        jPanelEmpleados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel12.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(127, 119, 119));
        jLabel12.setText("EMPLEADOS");
        jPanelEmpleados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 40));

        jPanelEmpleados1.setBackground(new java.awt.Color(231, 231, 216));
        jPanelEmpleados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazpi/images/salir.png"))); // NOI18N
        jPanelEmpleados1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel14.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(127, 119, 119));
        jLabel14.setText("salir");
        jPanelEmpleados1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 40));

        getContentPane().add(jPanelBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 490));

        javax.swing.GroupLayout jPaneMateriaPrimaTabbedLayout = new javax.swing.GroupLayout(jPaneMateriaPrimaTabbed);
        jPaneMateriaPrimaTabbed.setLayout(jPaneMateriaPrimaTabbedLayout);
        jPaneMateriaPrimaTabbedLayout.setHorizontalGroup(
            jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPaneMateriaPrimaTabbedLayout.setVerticalGroup(
            jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Materia Prima", jPaneMateriaPrimaTabbed);

        javax.swing.GroupLayout jPanelProductosTabbedLayout = new javax.swing.GroupLayout(jPanelProductosTabbed);
        jPanelProductosTabbed.setLayout(jPanelProductosTabbedLayout);
        jPanelProductosTabbedLayout.setHorizontalGroup(
            jPanelProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanelProductosTabbedLayout.setVerticalGroup(
            jPanelProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jPanelProductosTabbed);

        javax.swing.GroupLayout jPanelProveedoresTabbedLayout = new javax.swing.GroupLayout(jPanelProveedoresTabbed);
        jPanelProveedoresTabbed.setLayout(jPanelProveedoresTabbedLayout);
        jPanelProveedoresTabbedLayout.setHorizontalGroup(
            jPanelProveedoresTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanelProveedoresTabbedLayout.setVerticalGroup(
            jPanelProveedoresTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proveedores", jPanelProveedoresTabbed);

        javax.swing.GroupLayout jPanelClientesTabbedLayout = new javax.swing.GroupLayout(jPanelClientesTabbed);
        jPanelClientesTabbed.setLayout(jPanelClientesTabbedLayout);
        jPanelClientesTabbedLayout.setHorizontalGroup(
            jPanelClientesTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanelClientesTabbedLayout.setVerticalGroup(
            jPanelClientesTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", jPanelClientesTabbed);

        javax.swing.GroupLayout jPanelEmpleadosTabbedLayout = new javax.swing.GroupLayout(jPanelEmpleadosTabbed);
        jPanelEmpleadosTabbed.setLayout(jPanelEmpleadosTabbedLayout);
        jPanelEmpleadosTabbedLayout.setHorizontalGroup(
            jPanelEmpleadosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanelEmpleadosTabbedLayout.setVerticalGroup(
            jPanelEmpleadosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Empleados", jPanelEmpleadosTabbed);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 600, 450));

        jPanel6.setBackground(new java.awt.Color(40, 70, 85));

        jLabel1.setFont(new java.awt.Font("Mesa Grande", 0, 12)); // NOI18N
        jLabel1.setText("GESTION DE LA EMPRESA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogoBarra;
    private javax.swing.JPanel jPaneMateriaPrimaTabbed;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBarraLateral;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelClientesTabbed;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelEmpleados1;
    private javax.swing.JPanel jPanelEmpleadosTabbed;
    private javax.swing.JPanel jPanelMateriaPrima;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelProductosTabbed;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelProveedoresTabbed;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
