/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author santi
 */
public class ViewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewJFrame
     */
    public ViewJFrame() {
        initComponents();
    }
    
    public void addListenerBtnAgregarRawMaterial(ActionListener listenController){
        btnAgregarMp.addActionListener(listenController);
    }
    
    public void addListenerBtnEliminarRawMaterial(ActionListener listenController){
        btnEliminarMp.addActionListener(listenController);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBarraSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBarraLateral = new javax.swing.JPanel();
        jLabelLogoBarra = new javax.swing.JLabel();
        jPanelMateriaPrima = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelProductos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelProveedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPaneMateriaPrimaTabbed = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        barraBotonesMP = new javax.swing.JPanel();
        btnAgregarMp = new javax.swing.JButton();
        btnEliminarMp = new javax.swing.JButton();
        btnActualizarMp = new javax.swing.JButton();
        jScrollPaneMateriaPrima = new javax.swing.JScrollPane();
        jTableMateriaP = new javax.swing.JTable();
        jPanelAgregarMP = new javax.swing.JPanel();
        jPanelEligeProveedor = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelEligeMP = new javax.swing.JPanel();
        jComboBoxMP = new javax.swing.JComboBox<>();
        jPanelCantidad = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanelBorrarMP = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanelEdtiarMP = new javax.swing.JPanel();
        jPanelIdEditarMP = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanelNombreNuevoMP = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPaneProductosTabbed = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        barraBotonesProductos = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelAgregarProducto = new javax.swing.JPanel();
        jPanelEligeProducto = new javax.swing.JPanel();
        jComboBoxProductos = new javax.swing.JComboBox<>();
        jPanelCantidad1 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanelBorrarProducto = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jPanelEdtiarProducto = new javax.swing.JPanel();
        jPanelIdEditarProducto = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jPanelNombreNuevoProducto = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.Color.gray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraSuperior.setBackground(new java.awt.Color(40, 70, 85));
        jPanelBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("G E S T I O N   D E   L A   E M P R E S A");
        jPanelBarraSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 20));

        getContentPane().add(jPanelBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 620, 20));

        jPanelBarraLateral.setBackground(new java.awt.Color(40, 70, 85));
        jPanelBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_peque.png"))); // NOI18N
        jPanelBarraLateral.add(jLabelLogoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 110));

        jPanelMateriaPrima.setBackground(new java.awt.Color(209, 209, 185));
        jPanelMateriaPrima.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelMateriaPrimaMouseMoved(evt);
            }
        });
        jPanelMateriaPrima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMateriaPrimaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMateriaPrimaMouseExited(evt);
            }
        });
        jPanelMateriaPrima.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seeds_122867 (1).png"))); // NOI18N
        jPanelMateriaPrima.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 119, 119));
        jLabel4.setText("MATERIA PRIMA");
        jPanelMateriaPrima.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        jPanelProductos.setBackground(new java.awt.Color(209, 209, 185));
        jPanelProductos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelProductosMouseMoved(evt);
            }
        });
        jPanelProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProductosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelProductosMouseExited(evt);
            }
        });
        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 119, 119));
        jLabel6.setText("PRODUCTOS");
        jPanelProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d0e057c0f1324dffe016a4ec4ef1e928-icono-de-golpe-de-empanada.png"))); // NOI18N
        jPanelProductos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jPanelBarraLateral.add(jPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));
        jPanelProductos.getAccessibleContext().setAccessibleName("");

        jPanelProveedores.setBackground(new java.awt.Color(209, 209, 185));
        jPanelProveedores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelProveedoresMouseMoved(evt);
            }
        });
        jPanelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProveedoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelProveedoresMouseExited(evt);
            }
        });
        jPanelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 119, 119));
        jLabel8.setText("PROVEEDORES");
        jPanelProveedores.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proveedor.png"))); // NOI18N
        jPanelProveedores.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jPanelBarraLateral.add(jPanelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        jPanelClientes.setBackground(new java.awt.Color(209, 209, 185));
        jPanelClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseMoved(evt);
            }
        });
        jPanelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelClientesMouseExited(evt);
            }
        });
        jPanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(127, 119, 119));
        jLabel10.setText("CLIENTES");
        jPanelClientes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/male3_85205.png"))); // NOI18N
        jPanelClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        jPanelBarraLateral.add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        jPanelEmpleados.setBackground(new java.awt.Color(209, 209, 185));
        jPanelEmpleados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelEmpleadosMouseMoved(evt);
            }
        });
        jPanelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEmpleadosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEmpleadosMouseExited(evt);
            }
        });
        jPanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleado.png"))); // NOI18N
        jPanelEmpleados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(127, 119, 119));
        jLabel12.setText("EMPLEADOS");
        jPanelEmpleados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jPanelBarraLateral.add(jPanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 40));

        jPanelSalir.setBackground(new java.awt.Color(209, 209, 185));
        jPanelSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseMoved(evt);
            }
        });
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseExited(evt);
            }
        });
        jPanelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jPanelSalir.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(127, 119, 119));
        jLabel14.setText("SALIR");
        jPanelSalir.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        jPanelBarraLateral.add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 60));

        getContentPane().add(jPanelBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 490));

        jLabel19.setBackground(new java.awt.Color(187, 187, 187));
        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        jLabel19.setText("M A T E R I A   P R I M A");

        barraBotonesMP.setBackground(new java.awt.Color(209, 209, 185));
        barraBotonesMP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarMp.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAgregarMp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/create2.png"))); // NOI18N
        btnAgregarMp.setText("Agregar MP");
        btnAgregarMp.setBorderPainted(false);
        btnAgregarMp.setContentAreaFilled(false);
        btnAgregarMp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarMp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraBotonesMP.add(btnAgregarMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 59));

        btnEliminarMp.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnEliminarMp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnEliminarMp.setText("Eliminar MP");
        btnEliminarMp.setBorderPainted(false);
        btnEliminarMp.setContentAreaFilled(false);
        btnEliminarMp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarMp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraBotonesMP.add(btnEliminarMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 59));

        btnActualizarMp.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnActualizarMp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update2.png"))); // NOI18N
        btnActualizarMp.setText("Actualizar MP");
        btnActualizarMp.setBorderPainted(false);
        btnActualizarMp.setContentAreaFilled(false);
        btnActualizarMp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarMp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraBotonesMP.add(btnActualizarMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 59));

        jTableMateriaP.setToolTipText("");
        jScrollPaneMateriaPrima.setViewportView(jTableMateriaP);
        if (jTableMateriaP.getColumnModel().getColumnCount() > 0) {
            jTableMateriaP.getColumnModel().getColumn(0).setResizable(false);
            jTableMateriaP.getColumnModel().getColumn(1).setResizable(false);
            jTableMateriaP.getColumnModel().getColumn(2).setResizable(false);
            jTableMateriaP.getColumnModel().getColumn(3).setResizable(false);
        }
        jTableMateriaP.getAccessibleContext().setAccessibleName("inventarioMateriaPrima");

        jPanelAgregarMP.setBorder(javax.swing.BorderFactory.createTitledBorder("Comprar Materia Prima"));
        jPanelAgregarMP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEligeProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elige Proveedor", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEligeProveedorLayout = new javax.swing.GroupLayout(jPanelEligeProveedor);
        jPanelEligeProveedor.setLayout(jPanelEligeProveedorLayout);
        jPanelEligeProveedorLayout.setHorizontalGroup(
            jPanelEligeProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEligeProveedorLayout.setVerticalGroup(
            jPanelEligeProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeProveedorLayout.createSequentialGroup()
                .addComponent(jComboBox1)
                .addContainerGap())
        );

        jPanelAgregarMP.add(jPanelEligeProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 32, -1, -1));

        jPanelEligeMP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elige la Materia Prima", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanelEligeMPLayout = new javax.swing.GroupLayout(jPanelEligeMP);
        jPanelEligeMP.setLayout(jPanelEligeMPLayout);
        jPanelEligeMPLayout.setHorizontalGroup(
            jPanelEligeMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeMPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jComboBoxMP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEligeMPLayout.setVerticalGroup(
            jPanelEligeMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeMPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelAgregarMP.add(jPanelEligeMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 93, 180, -1));

        jPanelCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elige la Cantidad", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanelCantidadLayout = new javax.swing.GroupLayout(jPanelCantidad);
        jPanelCantidad.setLayout(jPanelCantidadLayout);
        jPanelCantidadLayout.setHorizontalGroup(
            jPanelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCantidadLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCantidadLayout.setVerticalGroup(
            jPanelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelAgregarMP.add(jPanelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 154, -1, -1));

        jPanelBorrarMP.setBorder(javax.swing.BorderFactory.createTitledBorder("ID a Borrar"));
        jPanelBorrarMP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelBorrarMP.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 121, -1));

        jPanelEdtiarMP.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Materia Prima"));
        jPanelEdtiarMP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIdEditarMP.setBorder(javax.swing.BorderFactory.createTitledBorder("ID a Editar"));

        javax.swing.GroupLayout jPanelIdEditarMPLayout = new javax.swing.GroupLayout(jPanelIdEditarMP);
        jPanelIdEditarMP.setLayout(jPanelIdEditarMPLayout);
        jPanelIdEditarMPLayout.setHorizontalGroup(
            jPanelIdEditarMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdEditarMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4)
                .addContainerGap())
        );
        jPanelIdEditarMPLayout.setVerticalGroup(
            jPanelIdEditarMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdEditarMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelEdtiarMP.add(jPanelIdEditarMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 34, 172, -1));

        jPanelNombreNuevoMP.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre nuevo"));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombreNuevoMPLayout = new javax.swing.GroupLayout(jPanelNombreNuevoMP);
        jPanelNombreNuevoMP.setLayout(jPanelNombreNuevoMPLayout);
        jPanelNombreNuevoMPLayout.setHorizontalGroup(
            jPanelNombreNuevoMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreNuevoMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNombreNuevoMPLayout.setVerticalGroup(
            jPanelNombreNuevoMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreNuevoMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5)
                .addContainerGap())
        );

        jPanelEdtiarMP.add(jPanelNombreNuevoMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 102, -1, -1));

        javax.swing.GroupLayout jPaneMateriaPrimaTabbedLayout = new javax.swing.GroupLayout(jPaneMateriaPrimaTabbed);
        jPaneMateriaPrimaTabbed.setLayout(jPaneMateriaPrimaTabbedLayout);
        jPaneMateriaPrimaTabbedLayout.setHorizontalGroup(
            jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraBotonesMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPaneMateriaPrimaTabbedLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneMateriaPrimaTabbedLayout.createSequentialGroup()
                        .addComponent(jPanelAgregarMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBorrarMP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanelEdtiarMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPaneMateriaPrimaTabbedLayout.setVerticalGroup(
            jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneMateriaPrimaTabbedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneMateriaPrimaTabbedLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneMateriaPrimaTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelEdtiarMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAgregarMP, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                    .addGroup(jPaneMateriaPrimaTabbedLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanelBorrarMP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(barraBotonesMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Materia Prima", jPaneMateriaPrimaTabbed);

        jLabel20.setBackground(new java.awt.Color(187, 187, 187));
        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        jLabel20.setText("P R O D U C T O S");

        barraBotonesProductos.setBackground(new java.awt.Color(209, 209, 185));
        barraBotonesProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProducto.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/create2.png"))); // NOI18N
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setBorderPainted(false);
        btnAgregarProducto.setContentAreaFilled(false);
        btnAgregarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        barraBotonesProductos.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 59));

        btnEliminarProducto.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.setContentAreaFilled(false);
        btnEliminarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraBotonesProductos.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 59));

        btnActualizarProducto.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnActualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update2.png"))); // NOI18N
        btnActualizarProducto.setText("Actualizar Producto");
        btnActualizarProducto.setBorderPainted(false);
        btnActualizarProducto.setContentAreaFilled(false);
        btnActualizarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraBotonesProductos.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 59));

        jTableProductos.setToolTipText("");
        jScrollPaneProductos.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setResizable(false);
            jTableProductos.getColumnModel().getColumn(1).setResizable(false);
            jTableProductos.getColumnModel().getColumn(2).setResizable(false);
            jTableProductos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanelAgregarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Producto"));
        jPanelAgregarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEligeProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elige la Materia Prima", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jComboBoxProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Papa Rellena", "Empanada", "Tuki", "Tukin't" }));

        javax.swing.GroupLayout jPanelEligeProductoLayout = new javax.swing.GroupLayout(jPanelEligeProducto);
        jPanelEligeProducto.setLayout(jPanelEligeProductoLayout);
        jPanelEligeProductoLayout.setHorizontalGroup(
            jPanelEligeProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeProductoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEligeProductoLayout.setVerticalGroup(
            jPanelEligeProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEligeProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelAgregarProducto.add(jPanelEligeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jPanelCantidad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elige la Cantidad", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanelCantidad1Layout = new javax.swing.GroupLayout(jPanelCantidad1);
        jPanelCantidad1.setLayout(jPanelCantidad1Layout);
        jPanelCantidad1Layout.setHorizontalGroup(
            jPanelCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCantidad1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCantidad1Layout.setVerticalGroup(
            jPanelCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCantidad1Layout.createSequentialGroup()
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanelAgregarProducto.add(jPanelCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 50));

        jPanelBorrarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("ID a Borrar"));
        jPanelBorrarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanelBorrarProducto.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 121, -1));

        jPanelEdtiarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Producto"));
        jPanelEdtiarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIdEditarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("ID a Editar"));

        javax.swing.GroupLayout jPanelIdEditarProductoLayout = new javax.swing.GroupLayout(jPanelIdEditarProducto);
        jPanelIdEditarProducto.setLayout(jPanelIdEditarProductoLayout);
        jPanelIdEditarProductoLayout.setHorizontalGroup(
            jPanelIdEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdEditarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField9)
                .addContainerGap())
        );
        jPanelIdEditarProductoLayout.setVerticalGroup(
            jPanelIdEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdEditarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelEdtiarProducto.add(jPanelIdEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 34, 172, -1));

        jPanelNombreNuevoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre nuevo"));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombreNuevoProductoLayout = new javax.swing.GroupLayout(jPanelNombreNuevoProducto);
        jPanelNombreNuevoProducto.setLayout(jPanelNombreNuevoProductoLayout);
        jPanelNombreNuevoProductoLayout.setHorizontalGroup(
            jPanelNombreNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreNuevoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNombreNuevoProductoLayout.setVerticalGroup(
            jPanelNombreNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreNuevoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10)
                .addContainerGap())
        );

        jPanelEdtiarProducto.add(jPanelNombreNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 102, -1, -1));

        javax.swing.GroupLayout jPaneProductosTabbedLayout = new javax.swing.GroupLayout(jPaneProductosTabbed);
        jPaneProductosTabbed.setLayout(jPaneProductosTabbedLayout);
        jPaneProductosTabbedLayout.setHorizontalGroup(
            jPaneProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraBotonesProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPaneProductosTabbedLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPaneProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneProductosTabbedLayout.createSequentialGroup()
                        .addComponent(jPanelAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanelEdtiarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPaneProductosTabbedLayout.setVerticalGroup(
            jPaneProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneProductosTabbedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPaneProductosTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEdtiarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAgregarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneProductosTabbedLayout.createSequentialGroup()
                        .addComponent(jPanelBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(barraBotonesProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Productos", jPaneProductosTabbed);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelMateriaPrimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMateriaPrimaMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanelMateriaPrimaMouseClicked

    private void jPanelMateriaPrimaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMateriaPrimaMouseMoved
        jPanelMateriaPrima.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelMateriaPrimaMouseMoved

    private void jPanelMateriaPrimaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMateriaPrimaMouseExited
        jPanelMateriaPrima.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelMateriaPrimaMouseExited

    private void jPanelProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductosMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanelProductosMouseClicked

    private void jPanelProductosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductosMouseMoved
        jPanelProductos.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelProductosMouseMoved

    private void jPanelProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductosMouseExited
        jPanelProductos.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelProductosMouseExited

    private void jPanelProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProveedoresMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelProveedoresMouseClicked

    private void jPanelProveedoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProveedoresMouseMoved
        jPanelProveedores.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelProveedoresMouseMoved

    private void jPanelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jPanelClientesMouseClicked

    private void jPanelClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseMoved
        jPanelClientes.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelClientesMouseMoved

    private void jPanelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelClientesMouseExited
        jPanelClientes.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelClientesMouseExited

    private void jPanelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpleadosMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jPanelEmpleadosMouseClicked

    private void jPanelEmpleadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpleadosMouseMoved
        jPanelEmpleados.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelEmpleadosMouseMoved

    private void jPanelEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmpleadosMouseExited
        jPanelEmpleados.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelEmpleadosMouseExited

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jPanelSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseMoved
        jPanelSalir.setBackground(new Color(216,200,232));
    }//GEN-LAST:event_jPanelSalirMouseMoved

    private void jPanelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseExited
        jPanelSalir.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelSalirMouseExited

    private void jPanelProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProveedoresMouseExited
        jPanelProveedores.setBackground(new Color(231,231,216));
    }//GEN-LAST:event_jPanelProveedoresMouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraBotonesMP;
    private javax.swing.JPanel barraBotonesProductos;
    private javax.swing.JButton btnActualizarMp;
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnAgregarMp;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEliminarMp;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxMP;
    private javax.swing.JComboBox<String> jComboBoxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogoBarra;
    private javax.swing.JPanel jPaneMateriaPrimaTabbed;
    private javax.swing.JPanel jPaneProductosTabbed;
    private javax.swing.JPanel jPanelAgregarMP;
    private javax.swing.JPanel jPanelAgregarProducto;
    private javax.swing.JPanel jPanelBarraLateral;
    private javax.swing.JPanel jPanelBarraSuperior;
    private javax.swing.JPanel jPanelBorrarMP;
    private javax.swing.JPanel jPanelBorrarProducto;
    private javax.swing.JPanel jPanelCantidad;
    private javax.swing.JPanel jPanelCantidad1;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelEdtiarMP;
    private javax.swing.JPanel jPanelEdtiarProducto;
    private javax.swing.JPanel jPanelEligeMP;
    private javax.swing.JPanel jPanelEligeProducto;
    private javax.swing.JPanel jPanelEligeProveedor;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelIdEditarMP;
    private javax.swing.JPanel jPanelIdEditarProducto;
    private javax.swing.JPanel jPanelMateriaPrima;
    private javax.swing.JPanel jPanelNombreNuevoMP;
    private javax.swing.JPanel jPanelNombreNuevoProducto;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JScrollPane jScrollPaneMateriaPrima;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMateriaP;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
